string=input()
capital_str = string.capitalize() #(only first letter in sentence)
title_case = string.title() #capitalizes 1st letter(all the words in sentence)
print(capital_str)
print(title_case)
